# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: windows-latest
    
    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: DeployAzureResources
  jobs:
    - job: DeployAzureResources
      pool:
        vmImage: 'windows-latest'
      steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'GiftCardAzureSubscription'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            # create and configure an Azure App Service plan and an Azure web app
            az appservice plan create -g $RESOURCEGROUPNAME -n $SVCPLANNAME --sku FREE
            az webapp create -g $RESOURCEGROUPNAME -p $SVCPLANNAME -n $WEBAPPNAMEAPI

- stage: DeployAPIApp
  jobs: 
  - job: DeployAPIApp
    pool: 
      vmImage: 'windows-latest'
    steps:

    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.DefaultWorkingDirectory)'

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'labAzureSubscription'
        appType: 'webApp'
        WebAppName: '$(WEBAPPNAMEAPI)'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

